language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install: composer install --no-interaction

script: vendor/bin/phpunit --coverage-clover=coverage/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
